name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Run unit tests with coverage
        run: |
          python -m pytest src/tests/unit -v --cov=src --cov-report=xml --junitxml=unit-test-results.xml --cov-branch

      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: |
            unit-test-results.xml
            coverage.xml
          retention-days: 30

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Run integration tests with coverage
        run: |
          python -m pytest src/tests/integration -v --cov=src --cov-report=xml:integration-coverage.xml --junitxml=integration-test-results.xml --cov-branch

      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: |
            integration-test-results.xml
            integration-coverage.xml
          retention-days: 30

  sonarcloud:
    name: SonarCloud Analysis
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest pytest-cov
      
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          path: test-results
          merge-multiple: true
      
      - name: Generate combined coverage report
        run: |
          coverage combine test-results/coverage.xml test-results/integration-coverage.xml || true
          coverage xml
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=dylan-teehan-skc_Metrics-Monitoring-System
            -Dsonar.organization=dylan-teehan-skc
            -Dsonar.python.version=3.11
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=src
            -Dsonar.tests=src/tests
            -Dsonar.test.inclusions=src/tests/**/*_test.py,src/tests/**/*_tests.py,src/tests/**/test_*.py
            -Dsonar.coverage.exclusions=src/tests/**/*,src/**/__init__.py,src/tests/**
            -Dsonar.junit.reportPaths=test-results/unit-test-results.xml,test-results/integration-test-results.xml 